# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      run: webapp
  template:
    metadata:
      labels:
        run: webapp
    spec:
      containers:
      - name: webapp
        # image: registry.k8s.io/hpa-example      
        image: cafc79/loginapi:0.4
        ports:
        - containerPort: 8080
          name: pod-custom-port
        resources:
          requests:
            cpu: 200m	          
          limits:
            cpu: 400m
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
