# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      run: webapp
  template:
    metadata:
      labels:
        run: webapp
    spec:
      containers:
      - name: webapp
        # image: registry.k8s.io/hpa-example      
        image: cafc79/loginapi:0.5
        ports:
        - containerPort: 8082
          name: pod-custom-port
        #resources:
          #requests:
            #cpu: 200m	          
          #limits:
            #cpu: 400m
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 10
