apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      run: webapp
  template:
    metadata:
      labels:
        run: webapp
    spec:
      containers:
      - name: webapp
        #image: registry.k8s.io/hpa-example      
        image: cafc79/loginapiservice-demo
        ports:
        - containerPort: 8080
          name: pod-custom-port
        resources:
          limits:
            cpu: 400m
          requests:
            cpu: 200m

