# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
      annotations:
        splunk.com/index: "k8s_metrics"
    spec:
      containers:
      - name: webapp
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: splunk-otel-collector
        image: quay.io/signalfx/splunk-otel-collector:latest
        env:
        - name: SPLUNK_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: splunk-secret
              key: access_token
        - name: SPLUNK_REALM
          value: "us0"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=chaos-testing"
