apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: login20-dummy  
spec:
  selector:
    app: loginapi
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8080
  externalIPs:
    - 1.2.4.114