#kubectl autoscale deployment webapp --cpu-percent=50 --min=1 --max=10
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-webapp
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: webapp
 minReplicas: 1
 maxReplicas: 10
 metrics:
 - type: Resource
   resource:
     name: cpu
      type: Utilization
      averageUtilization: 50
      #targetAverageUtilization: 50
 - type: Resource
   resource:
     name: memory
     target:
       type: AverageValue
       averageValue: 128Mi  
status:
  observedGeneration: 1
  lastScaleTime: 10
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      currentAverageUtilization: 0
      currentAverageValue: 0
