#kubectl autoscale deployment webapp --cpu-percent=50 --min=1 --max=10
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-webapp
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: webapp
 minReplicas: 1
 maxReplicas: 10
 metrics:
 - type: Resource
   resource:
     name: cpu
     target:
       type: Utilization
       averageUtilization: 50
 - type: Resource
   resource:
     name: memory
     target:
       type: AverageValue
       averageValue: 256Mi 
 - type: Object
   object:
       metric:
         name: requests-per-second
       describedObject:
         apiVersion: networking.k8s.io/v1beta1
         kind: Ingress
         name: main-route
       target:
         type: Value
         value: 10k
