apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
  - default:
      memory: 64Mi
      cpu: 100m
    defaultRequest:
      cpu: 100m
      memory: 64Mi
    type: Container
