apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: login20-dummy
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/"
    type: Directory