apiVersion: v1
kind: Service
metadata:
  name: svc-webapp
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
  labels:
    run: webapp
spec:
  ports:
  - port: 8080
  externalIPs:
    - 1.2.4.114
  selector:
    run: webapp  
  type: LoadBalancer
