apiVersion: v1
kind: Service
metadata:
  name: svc-loginapi
  namespace: login20-dummy
  labels:
    run: loginapi  
    app: loginapi
    app.profuturo.mx/zone: dev
    app.profuturo.mx/version: v3
    app.profuturo.mx/phase: test-mtls
    app.profuturo.mx/tier: backend
    app.profuturo.mx/client: mx.profuturo
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    run: loginapi
