apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-example
  namespace: default
spec:
  action: pod-failure
  mode: one
  selector:
    labelSelectors:
      app: webapp
  duration: "30s" # Tiempo que permanecerá el pod eliminado
  scheduler:
    cron: "@every 2m" # Cada 2 minutos